### ISSUE TITLE
guess module for nuxt

### ISSUE THREAD

**Issue by clarkdo** [daliborgogic/guess-module#11]
Hi @daliborgogic, sorry about that I didn't notice there is a guess-module here, I create a duplicated on in https://github.com/nuxt-community/guess-module and published 0.1.1.

I'll invite you as that repo's collaborator, sorry about that again.

**Comment by clarkdo** [comment]
Pls check https://github.com/nuxt-community/guess-module/invitations

**Comment by daliborgogic** [comment]
Hi @clarkdo , no problemo.
